### ISSUE TITLE
Please update Packagist

### ISSUE THREAD

**Issue by michalper** [rdohms/phpunit-arraysubset-asserts#16]
Hi,

thanks for yesterday PHPUnit 9.0 merge, but please update your packagist:
https://packagist.org/packages/dms/phpunit-arraysubset-asserts

I've still got an error when I've tried to update to 0.2 version:

`  Problem 1
    - The requested package dms/phpunit-arraysubset-asserts ^0.2.0 exists as dms/phpunit-arraysubset-asserts[dev-master, v0.1.0] but these are rejected by your constraint.`

**Comment by rdohms** [comment]
I have hit the manual update, should be good to go now.
