### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sandervanhooft** [rdohms/phpunit-arraysubset-asserts#2]
Hi @rdohms,

Thanks for providing this! ❤️ 

Could you perhaps include a license (my preference goes to MIT)?

Cheers,

Sander

**Comment by sandervanhooft** [comment]
(I'm hesitant to use this package in my open source work now because there's no license included)

**Comment by rdohms** [comment]
@sandervanhooft oh yeah of course, i added it in the composer.json but forgot to add the LICENSE file. will do.
