### ISSUE TITLE
Does not work on PHPUnit 8

### ISSUE THREAD

**Issue by Bilge** [rdohms/phpunit-arraysubset-asserts#50]
This library makes the (wrong) assumption that we should not want to use it (even though we installed it for some reason) on PHPUnit 8, with its custom autoloader that makes the `ArraySubsetAsserts` trait do nothing. In that case, PHPUnit 8's implementation will run as normal and issue a deprecation warning, which will also cause the tests to fail if `failOnWarning="true"` is being used in the PHPUnit config. I should think that if this library is installed, it's a fair bet we want to use it.

**Comment by jrfnl** [comment]
@Bilge I'm not sure I understand your remark. Prior to the last release, the library couldn't even be installed in combination with PHPUnit 8.

**Comment by marcosh** [comment]
Happened to me, too. I installed this library to get rid of the warnings in PHPUnit8 but I still got them. It would be nice to have the chance to choose to use the library code instead of the one provided by PHPUnit

**Comment by jrfnl** [comment]
PR #65 should address this. Testing appreciated.
