### ISSUE TITLE
Major necessary?

### ISSUE THREAD

**Issue by dereuromark** [rdohms/phpunit-arraysubset-asserts#53]
Just a small question, not necessarily something wrong:

We are using your library and follow semver 2.0.
Was there any BC break or what was the reason for 0.3 release after 0.2?
As that is a (semantic) major release and thus will not work to pull without a major constraint update on our side.
Or in other words: `0.2.2` as semantic minor wouldn't have worked?
Thank you

Either way, we will update our dependency constraints accordingly.
But if there was indeed a mistake, maybe we can go for more minors then in the future for example.

**Comment by rdohms** [comment]
Hi,

There was significant work done on the polyfills that I judged enough for a new version zero release, as it impacts the non-code API of the project and its usage in certain scenarios, especially for those on older versions.

Had we already been on a v1 release it would have been a minor, but in this case, it was the next step in our API evolution that I wanted to punctuate.
