### ISSUE TITLE
Support PHPStan 1.7.0

### ISSUE THREAD

**Issue by simPod** [rdohms/phpunit-arraysubset-asserts#67]
Current autoloading scheme is broken on phpstan 1.7.0 since it does not run code anymore (uses static reflection)

Specifically, it now reports `Call to an undefined static method My\Ns\ATest::assertArraySubset()` because this trait exists https://github.com/rdohms/phpunit-arraysubset-asserts/blob/master/src/ArraySubsetAssertsEmpty.php

**Comment by rdohms** [comment]
It looks like PHPStan fixed this on their end. If this is not the case @simPod, please re-open so we can figure out what can be done.
