### ISSUE TITLE
PHPUnit 10 Compatibility

### ISSUE THREAD

**Issue by technosailor** [rdohms/phpunit-arraysubset-asserts#74]
Is there a timeline that can be expected for PHPUnit ^10.0 compatibility? Currently, we use Pest for unit testing and Pest 2.0 requires phpunit ^10.0 and this library doesn't support that yet. Is there a technical thing maybe I can lend a hand to, or is it as simple as the requirements have not been updated?

**Comment by jrfnl** [comment]
See #70

**Comment by rdohms** [comment]
Released in v0.5.0
